#!/usr/bin/env python3
"""Does a basis the mechanical state generates beat a fixed one of equal rank?

Every reduction tried so far asked one fixed low-dimensional object to carry the
plastic field, and every one failed. The premise is now identified as the fault
rather than the methods: nothing requires the field to lie on a global manifold.
What must be small is the space of admissible plastic corrections *around the
current state*.

```text
refuted     eps_p_n = Phi a_n             one fixed Phi(x) for every state
here        eps_p_n = Phi(S_n) a_n        a basis the current state generates
```

The inverse still solves for `r` numbers per increment. Those numbers no longer
encode an image; they weight directions the mechanics itself produced.

This is the first rung, and it deliberately carries **no learning at all**. A
trained generator can hide the answer inside the basis -- with enough capacity a
rank-one `Phi` equal to the required correction drives the error to zero at
`r = 1`, which is the surjectivity of `A` returning one level up. Before
spending anything on that machinery it is worth knowing whether state dependence
buys anything, and an analytic state-generated basis answers exactly that at no
risk. If a hand-built one already beats Krylov at equal rank, a learned one has
something to improve on; if it does not, we have learned that cheaply.

Three bases, same increments, same ranks, same masked fit:

```text
free      the unconstrained inverse            an upper bound on what fits
krylov    residual-driven, fixed for all n     the refuted premise
aligned   m_k(sigma_eq(x)) N(sigma_bar(x))     generated by the current state
```

The `aligned` modes carry the plastic direction of the current stress with an
amplitude that depends on the local equivalent stress and on nothing else. No
coordinate enters, so the basis cannot encode a map of the specimen: mode `k`
says "yield wherever the equivalent stress sits in band `k`", and its
coefficient is the plastic multiplier for that band. The set of `r` coefficients
is a free-form hardening response, read off the data instead of assumed. That
also sidesteps the reduced dissipation cone, which is otherwise expected to be
trivial -- `C a >= 0` is millions of half-spaces intersected in `R^8`, and the
Krylov cone already admitted only `q = 0` at every rank. Here
`D = m_k (sigma . N) = m_k |dev sigma| >= 0` pointwise for any `m_k >= 0`, so
the constraint collapses to `r` sign conditions and is enforced by an NNLS.

Two conventions decide whether any of this means anything, and both are checked
at startup rather than trusted.

`operator.elasticity` is the **Kelvin** stiffness, `kinematics.strain` returns
**engineering** shear, and `divergence_from_sample_stress` expects **Voigt**.
Chaining the three without conversion silently doubles the shear stress. The
elastic lifting in `qualify_subspace_prediction_and_dissipation_p43.py` and its
siblings does exactly that, and the field it returns is not in equilibrium: it
retains 32 % of the interior residual where the converted form reaches 4e-16.
`elastic_lift` below converts, and `main` asserts the residual it achieves.

The operator is self-adjoint up to the elasticity, `A = E C` with `E = B K^-1
B^T` symmetric, so `A^T = C E`. A dot-product test runs before anything else.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np
from scipy.optimize import nnls
from scipy.sparse.linalg import LinearOperator, lsqr

from fem_inhouse.core.kelvin import KELVIN_SCALE_2D
from fem_inhouse.identification.tensor_plastic_observability import (
    TensorPlasticObservabilityOperator,
)
from fem_inhouse.spectral2d.grid import StructuredGrid2D
from fem_inhouse.spectral2d.newton_ebi import pack_interior, unpack_interior

ROOT = Path(__file__).resolve().parents[1]
HISTORY = (
    ROOT
    / "validation/reference_data/dic_multistep_history_p0043_repaired_v1"
    / "repaired_history_mm.npy"
)
PIXEL_SIZE_MM = 0.00184
YOUNG_MPA = 205_000.0
POISSON = 0.30


class _Identity:
    def apply(self, values):
        return np.asarray(values, dtype=np.float64)

    def adjoint(self, values):
        return np.asarray(values, dtype=np.float64)


def von_mises_plane_stress(stress_kelvin: np.ndarray) -> np.ndarray:
    """Equivalent stress from Kelvin components, with `sigma_zz = 0`."""

    xx, yy = stress_kelvin[:, 0], stress_kelvin[:, 1]
    xy = stress_kelvin[:, 2] / np.sqrt(2.0)
    return np.sqrt(np.maximum(xx**2 - xx * yy + yy**2 + 3.0 * xy**2, 0.0))


def deviatoric_direction(stress_kelvin: np.ndarray) -> np.ndarray:
    """Unit plastic flow direction, in-plane Kelvin, for `sigma_zz = 0`.

    The in-plane part of a three-dimensional deviator is not trace free -- plane
    stress fixes `eps_zz = -(eps_xx + eps_yy)` instead -- so nothing here is
    projected onto a trace-free in-plane subspace. The norm is the full
    three-dimensional one, which is what makes `sigma . N` equal `|dev sigma|`
    and therefore makes any non-negative amplitude dissipative.
    """

    xx, yy = stress_kelvin[:, 0], stress_kelvin[:, 1]
    xy = stress_kelvin[:, 2] / np.sqrt(2.0)
    pressure = (xx + yy) / 3.0
    dxx, dyy, dzz = xx - pressure, yy - pressure, -pressure
    norm = np.sqrt(np.maximum(dxx**2 + dyy**2 + dzz**2 + 2.0 * xy**2, 1e-300))
    return np.stack([dxx, dyy, np.sqrt(2.0) * xy], axis=1) / norm[:, None]


def stress_band_basis(stress_kelvin: np.ndarray, rank: int, mask: np.ndarray) -> np.ndarray:
    """`r` modes: the current flow direction, banded by equivalent stress.

    The band centres are quantiles of the equivalent stress over the fitting
    region only, so the held-out region never influences the basis either. The
    bumps overlap, which keeps the basis from being a partition of unity with
    hard edges and keeps `A Phi` better conditioned.
    """

    equivalent = von_mises_plane_stress(stress_kelvin)
    direction = deviatoric_direction(stress_kelvin)
    quantiles = np.linspace(0.0, 1.0, rank + 2)[1:-1]
    centres = np.quantile(equivalent[mask], quantiles)
    width = max(float(np.diff(centres).mean()) if rank > 1 else 1.0, 1e-12)
    bumps = np.exp(-0.5 * ((equivalent[:, None] - centres[None, :]) / width) ** 2)
    return direction[:, :, None] * bumps[:, None, :]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--origin", nargs=2, type=int, default=(1580, 1030))
    parser.add_argument("--pixels", type=int, default=100)
    parser.add_argument("--reference-state", type=int, default=20)
    parser.add_argument("--states", nargs="+", type=int, default=list(range(21, 41)))
    parser.add_argument("--ranks", nargs="+", type=int, default=[2, 4, 8, 16, 32])
    parser.add_argument("--holdout", nargs=3, type=int, default=(35, 35, 30),
                        help="row, column and side of the held-out square, in pixels")
    parser.add_argument("--ridge", type=float, default=1e-8)
    parser.add_argument("--output", type=Path, required=True)
    arguments = parser.parse_args()

    pixels = arguments.pixels
    x0, y0 = arguments.origin
    grid = StructuredGrid2D(pixels, pixels, PIXEL_SIZE_MM * pixels, PIXEL_SIZE_MM * pixels)
    operator = TensorPlasticObservabilityOperator.build(
        grid,
        young_modulus_mpa=YOUNG_MPA,
        poisson_ratio=POISSON,
        transfer=_Identity(),
        whitener=_Identity(),
    )
    points = operator.kinematics.material_point_count

    def kelvin_strain(field) -> np.ndarray:
        return operator.kelvin_strain(field).reshape(-1, 3)

    def stress_of(strain: np.ndarray) -> np.ndarray:
        return np.einsum("pi,pij->pj", strain.reshape(-1, 3), operator.elasticity)

    def divergence(stress_kelvin: np.ndarray) -> np.ndarray:
        voigt = stress_kelvin.reshape(-1, 3) / KELVIN_SCALE_2D
        return pack_interior(
            operator.kinematics.divergence_from_sample_stress(
                voigt.reshape((pixels, pixels, 2, 3))
            )
        )

    def elastic_lift(field: np.ndarray) -> np.ndarray:
        """The equilibrated field carrying the same boundary displacements."""

        forcing = -divergence(stress_of(kelvin_strain(field))) / operator.quadrature_weight
        lifted = field.copy()
        lifted[1:-1, 1:-1, :] -= operator.solve_stiffness(forcing).reshape(
            pixels - 1, pixels - 1, 2
        )
        return lifted

    def interior_residual(field: np.ndarray) -> float:
        return float(np.linalg.norm(divergence(stress_of(kelvin_strain(field)))))

    def green(values: np.ndarray) -> np.ndarray:
        """`E = B K^-1 B^T`, symmetric, from a Kelvin dual field to Kelvin strain."""

        displacement = unpack_interior(
            operator.solve_stiffness(operator._strain_transpose(values.reshape(-1))), grid
        )
        return kelvin_strain(displacement)

    def apply(plastic: np.ndarray) -> np.ndarray:
        return green(stress_of(plastic))

    def apply_transpose(values: np.ndarray) -> np.ndarray:
        return stress_of(green(values.reshape(-1, 3)))

    # Milestone 3 in miniature: the chain is only usable if its adjoint is the
    # adjoint. `A = E C` with `E` symmetric and `C` symmetric, so `A^T = C E`.
    generator = np.random.default_rng(20260816)
    left = generator.standard_normal((points, 3))
    right = generator.standard_normal((points, 3))
    forward = float((apply(left) * right).sum())
    backward = float((left * apply_transpose(right)).sum())
    discrepancy = abs(forward - backward) / max(abs(forward), 1e-300)
    print(f"adjoint dot-product test: {discrepancy:.3e}", flush=True)
    if discrepancy > 1e-8:
        raise AssertionError(f"adjoint inconsistent at {discrepancy:.3e}")

    report = json.loads((HISTORY.with_name("report.json")).read_text(encoding="utf-8"))
    bounds = list(map(int, report["solve_bounds"]))
    source = np.load(HISTORY, mmap_mode="r", allow_pickle=False)
    history = np.asarray(
        source[
            :,
            x0 - bounds[0] : x0 + pixels - bounds[0] + 1,
            y0 - bounds[2] : y0 + pixels - bounds[2] + 1,
            :,
        ],
        dtype=np.float64,
    )
    reference = history[arguments.reference_state]

    residual_before = interior_residual(history[40] - reference)
    residual_after = interior_residual(elastic_lift(history[40] - reference))
    print(f"elastic lifting: interior residual {residual_before:.3e} -> "
          f"{residual_after:.3e} ({residual_after / residual_before:.2e} relative)", flush=True)
    if residual_after / residual_before > 1e-10:
        raise AssertionError("the elastic lifting does not equilibrate")

    # The held-out square, in material points. Each pixel carries two subcells.
    row, column, side = arguments.holdout
    held = np.zeros((pixels, pixels, 2), dtype=bool)
    held[row : row + side, column : column + side, :] = True
    held = held.reshape(-1)
    fit = ~held
    print(f"{points} material points, {100 * held.mean():.1f} % held out", flush=True)

    states = arguments.states
    measured = {s: kelvin_strain(history[s] - reference) for s in states}
    elastic = {s: kelvin_strain(elastic_lift(history[s] - reference)) for s in states}
    reference_stress = stress_of(kelvin_strain(reference))

    def scores(simulated: np.ndarray, state: int) -> tuple[float, float]:
        """Share of the elastic defect that survives, fitted and held out."""

        defect = measured[state] - elastic[state]
        remaining = measured[state] - simulated
        return (
            float(np.linalg.norm(remaining[fit]) / np.linalg.norm(defect[fit])),
            float(np.linalg.norm(remaining[held]) / np.linalg.norm(defect[held])),
        )

    def reduced_solve(responses: np.ndarray, target: np.ndarray, non_negative: bool):
        """Least squares on the fitting region only, ridged, optionally `a >= 0`.

        The coefficients are global, so a target covering the whole field would
        pull the held-out region into the fit. Eight numbers leak little; at
        rank 32 it is no longer negligible, and masking costs nothing.
        """

        matrix = responses[fit.repeat(3)]
        vector = target.reshape(-1)[fit.repeat(3)]
        scale = max(float(np.linalg.norm(matrix)), 1e-300)
        augmented = np.concatenate(
            [matrix, np.sqrt(arguments.ridge) * scale * np.eye(matrix.shape[1])]
        )
        extended = np.concatenate([vector, np.zeros(matrix.shape[1])])
        if non_negative:
            coefficients, _ = nnls(augmented, extended)
            return coefficients
        coefficients, *_ = np.linalg.lstsq(augmented, extended, rcond=None)
        return coefficients

    def krylov_basis(size: int) -> np.ndarray:
        """Residual-driven and fixed: the premise this campaign is testing."""

        seeds = [apply_transpose(measured[s] - elastic[s]).reshape(-1) for s in states]
        basis, _ = np.linalg.qr(np.asarray(seeds).T)
        columns, total = [basis], basis.shape[1]
        while total < size:
            grown = np.asarray(
                [apply_transpose(apply(columns[-1][:, k])).reshape(-1)
                 for k in range(columns[-1].shape[1])]
            ).T
            orthonormal, _ = np.linalg.qr(np.concatenate([*columns, grown], axis=1))
            addition = orthonormal[:, total:]
            if addition.shape[1] == 0:
                break
            columns.append(addition)
            total += addition.shape[1]
        return np.concatenate(columns, axis=1)[:, :size]

    results: dict[str, dict] = {}

    # The free field, once: an upper bound on what any basis can reach.
    free_fit, free_held = [], []
    plastic = np.zeros((points, 3))
    rows = fit.repeat(3)
    for state in states:
        target = (measured[state] - elastic[state] - apply(plastic)).reshape(-1)[rows]
        linear = LinearOperator(
            (int(rows.sum()), points * 3),
            matvec=lambda v: apply(v).reshape(-1)[rows],
            rmatvec=lambda v: apply_transpose(_scatter(v, rows, points)).reshape(-1),
            dtype=np.float64,
        )
        increment = lsqr(linear, target, atol=1e-10, btol=1e-10, iter_lim=400)[0]
        plastic = plastic + increment.reshape(-1, 3)
        a, b = scores(elastic[state] + apply(plastic), state)
        free_fit.append(a)
        free_held.append(b)
    results["free"] = {"fitted": free_fit, "held_out": free_held}
    print(f"free field      : fitted {free_fit[-1]:.4f}  held out {free_held[-1]:.4f}", flush=True)

    fixed = krylov_basis(max(arguments.ranks))
    for rank in arguments.ranks:
        for name in ("krylov", "aligned"):
            plastic = np.zeros((points, 3))
            history_fit, history_held, dissipation = [], [], []
            previous_stress = reference_stress
            for state in states:
                predictor = elastic[state] + apply(plastic)
                stress = reference_stress + stress_of(predictor - plastic)
                target = measured[state] - predictor
                if name == "krylov":
                    modes = fixed[:, :rank].reshape(points, 3, rank)
                    non_negative = False
                else:
                    modes = stress_band_basis(stress, rank, fit)
                    non_negative = True
                responses = np.stack(
                    [apply(modes[:, :, k]).reshape(-1) for k in range(rank)], axis=1
                )
                singular = np.linalg.svd(responses, compute_uv=False)
                coefficients = reduced_solve(responses, target, non_negative)
                increment = modes @ coefficients
                plastic = plastic + increment
                simulated = elastic[state] + apply(plastic)
                new_stress = reference_stress + stress_of(simulated - plastic)
                dissipation.append(
                    (0.5 * (previous_stress + new_stress) * increment).sum(axis=1)
                )
                previous_stress = new_stress
                a, b = scores(simulated, state)
                history_fit.append(a)
                history_held.append(b)
            power = np.asarray(dissipation)
            results[f"{name}_r{rank}"] = {
                "fitted": history_fit,
                "held_out": history_held,
                "negative_dissipation_fraction": float((power < 0.0).mean()),
                "conditioning_of_A_Phi": float(singular[0] / max(singular[-1], 1e-300)),
                "effective_rank": int((singular > 1e-8 * singular[0]).sum()),
            }
            print(
                f"{name:8s} r={rank:2d}: fitted {history_fit[-1]:.4f}  "
                f"held out {history_held[-1]:.4f}  "
                f"negative dissipation {100 * (power < 0.0).mean():.2f} %  "
                f"cond {singular[0] / max(singular[-1], 1e-300):.2e}  "
                f"effective rank {int((singular > 1e-8 * singular[0]).sum())}",
                flush=True,
            )

    arguments.output.parent.mkdir(parents=True, exist_ok=True)
    arguments.output.write_text(
        json.dumps(
            {
                "schema_version": 1,
                "origin_nodes": [x0, y0],
                "pixels": pixels,
                "states": states,
                "ranks": arguments.ranks,
                "holdout": list(arguments.holdout),
                "held_out_fraction": float(held.mean()),
                "metric": (
                    "share of the elastic defect surviving: "
                    "|eps_measured - eps_sim| / |eps_measured - eps_elastic|"
                ),
                "adjoint_discrepancy": discrepancy,
                "results": results,
            },
            indent=2,
            sort_keys=True,
        )
        + "\n",
        "utf-8",
    )
    print(f"wrote {arguments.output}")
    return 0


def _scatter(values: np.ndarray, rows: np.ndarray, points: int) -> np.ndarray:
    full = np.zeros(points * 3)
    full[rows] = values
    return full


if __name__ == "__main__":
    raise SystemExit(main())
