#!/usr/bin/env python3
"""Milestone 2: qualify the local-coefficient inverse chain, without a network.

The numerical barrier is low enough that it is no longer the binding risk. The
question is now whether the local plastic representation is **identifiable**,
and this script answers the part of it that does not need a generator:

```text
a  ->  Delta p  ->  P_H  ->  equilibrium  ->  J(u; u_obs)  ->  grad_a J
```

Gates, registered in `validation/local_coefficient_inverse_preregistration.md`
before any run and not to be moved afterwards:

1. the transpose is the transpose, dot product below 1e-10;
2. the gradient is the derivative of the objective, central differences below
   1e-5 at the best step **and** a V-shaped sweep;
3. twin recovery from a known `a_true`, objective down three decades and field
   error below 5 % at `q = 1`;
4. admissibility holds at every iterate;
5. the warm regime survives real descent steps, median Newton at most 2.

Gate 3 is the point. Fitting a displacement proves little on its own -- the
eigenstrain operator is surjective -- so what is tested here is whether the
inverse *in coefficient space* is well posed when the data were generated by
exactly this forward model. A representation that cannot be recovered under
those conditions will not be recovered from real data by adding capacity.
"""

from __future__ import annotations

import argparse
import json
import time
from pathlib import Path

import numpy as np
from bench_local_coefficients_nonlinear import uniaxial_boundary
from qualify_full_field_plastic_operator import FullFieldPlasticOperator
from scipy.optimize import minimize
from scipy.sparse.linalg import LinearOperator

from fem_inhouse.core.driven_j2 import DrivenJ2PlaneStressBatch
from fem_inhouse.identification.local_coefficient_inverse import (
    AdmissibleProjection,
    LocalCoefficientInverse,
    SeparableLocalBasis,
)
from fem_inhouse.spectral2d.grid import StructuredGrid2D
from fem_inhouse.spectral2d.kinematics import TwoSubcellDiagnostic2D
from fem_inhouse.workflows.experimental_mechanical_oracle import (
    evaluate_experimental_mechanical_oracle,
)

PIXEL_SIZE_MM = 0.00184
YOUNG_MPA = 205_000.0
POISSON = 0.30


def build(pixels: int, patches: int, degree: int):
    grid = StructuredGrid2D(
        pixels, pixels, PIXEL_SIZE_MM * pixels, PIXEL_SIZE_MM * pixels
    )
    kinematics = TwoSubcellDiagnostic2D(grid)
    material = DrivenJ2PlaneStressBatch(
        kinematics.material_point_count,
        young_modulus_mpa=YOUNG_MPA,
        poisson_ratio=POISSON,
    )
    spectral = FullFieldPlasticOperator(
        grid, backend="fftw", workers=8, kernel="generic",
        pad_transform=0, planner="estimate",
    )
    preconditioner = LinearOperator(
        (spectral.size, spectral.size), matvec=spectral.precondition, dtype=np.float64
    )
    basis = SeparableLocalBasis.build(grid.nx, grid.ny, patches, degree)
    return grid, kinematics, material, preconditioner, basis


def smooth_coefficients(basis: SeparableLocalBasis, peak: float, seed: int) -> np.ndarray:
    """A non-negative constant mode with small higher modes on top."""

    generator = np.random.default_rng(seed)
    values = np.zeros(basis.coefficient_shape)
    values[:, :, 0, 0] = np.abs(generator.standard_normal(values.shape[:2]))
    if values.shape[2] > 1:
        higher = generator.standard_normal(values.shape) * 0.15
        higher[:, :, 0, 0] = 0.0
        values += higher
    values *= peak / values[:, :, 0, 0].max()
    return values


def settle(inverse: LocalCoefficientInverse, material, kinematics, grid,
           preconditioner, coefficients, increments: int, strain: float) -> None:
    """Advance a few committed increments so the state is genuinely plastic."""

    from fem_inhouse.workflows.experimental_mechanical_oracle import (
        solve_fixed_plastic_increment_equilibrium,
    )

    projected, _, _ = inverse._increment_from(coefficients)
    subcells = kinematics.material_point_count // (grid.nx * grid.ny)
    increment = np.repeat(projected[:, :, None], subcells, axis=2)
    displacement = None
    for step in range(1, increments + 1):
        result = solve_fixed_plastic_increment_equilibrium(
            material=material, kinematics=kinematics,
            boundary_displacement=uniaxial_boundary(grid, step * strain),
            equivalent_plastic_increment=increment,
            initial_displacement=displacement,
            equilibrium_rms_tolerance=1e-10,
            maximum_krylov_iterations=3000,
            preconditioner=preconditioner,
        )
        displacement = result.displacement
        material.commit()
    inverse._warm_displacement = displacement


# -- gate 1 ---------------------------------------------------------------


def gate_transpose(arguments) -> dict:
    """`<J(du,dp), y> == <du, JT(y)_u> + <dp, JT(y)_p>`, exact linear algebra."""

    grid, kinematics, material, _, _ = build(arguments.small_pixels, 4, 0)
    generator = np.random.default_rng(11)
    points = kinematics.material_point_count
    strain = 1.2e-3
    displacement = uniaxial_boundary(grid, strain)
    plastic = np.full((grid.nx, grid.ny, 2), 2.0e-4)
    linearisation = evaluate_experimental_mechanical_oracle(
        material=material, kinematics=kinematics, displacement=displacement,
        equivalent_plastic_increment=plastic, time_increment=1.0,
    )
    worst = 0.0
    for _ in range(4):
        du = generator.standard_normal(linearisation.displacement_shape)
        dp = generator.standard_normal(linearisation.plastic_increment_shape)
        y = generator.standard_normal(linearisation.displacement_shape)
        forward = linearisation.jacobian_action(du, dp)
        dual_u, dual_p = linearisation.jacobian_transpose_action(y)
        left = float(np.sum(forward * y))
        right = float(np.sum(du * dual_u) + np.sum(dp * dual_p))
        worst = max(worst, abs(left - right) / max(abs(left), abs(right), 1e-300))
    print(f"  gate 1  transpose dot product, worst relative: {worst:.3e}", flush=True)
    return {"worst_relative": worst, "points": points, "passed": worst <= 1e-10}


# -- gate 2 ---------------------------------------------------------------


def gate_gradient(arguments) -> dict:
    """Central differences against the adjoint, over a step sweep."""

    report: dict[str, object] = {}
    for degree in arguments.degrees:
        grid, kinematics, material, preconditioner, basis = build(
            arguments.small_pixels, arguments.small_patches, degree
        )
        peak = arguments.peak_increment
        truth = smooth_coefficients(basis, peak, 5)
        inverse = LocalCoefficientInverse(
            material=material, kinematics=kinematics, grid=grid, basis=basis,
            boundary_displacement=uniaxial_boundary(grid, arguments.strain),
            observed_displacement=np.zeros((grid.nx + 1, grid.ny + 1, 2)),
            preconditioner=preconditioner,
            projection=AdmissibleProjection(safety=arguments.safety),
        )
        observed, _, _ = inverse.evaluate(truth)
        inverse.observed_displacement = observed.displacement.copy()

        start = truth * 0.6
        _, gradient = inverse.gradient(start)
        generator = np.random.default_rng(7)
        directions = [generator.standard_normal(basis.coefficient_shape) for _ in range(2)]
        per_direction = []
        for index, direction in enumerate(directions):
            direction = direction / np.linalg.norm(direction) * np.linalg.norm(start)
            analytic = float(np.sum(gradient * direction))
            sweep = []
            for exponent in range(2, 9):
                step = 10.0 ** (-exponent)
                plus, _, _ = inverse.evaluate(start + step * direction)
                minus, _, _ = inverse.evaluate(start - step * direction)
                difference = (plus.objective - minus.objective) / (2.0 * step)
                relative = abs(difference - analytic) / max(abs(analytic), 1e-300)
                sweep.append({"step": step, "finite_difference": difference,
                              "relative_error": relative})
                print(f"  gate 2  q={(degree + 1) ** 2} dir {index} h=1e-{exponent}  "
                      f"fd={difference:+.8e}  adj={analytic:+.8e}  rel={relative:.3e}",
                      flush=True)
            errors = [row["relative_error"] for row in sweep]
            best = min(errors)
            # A wrong gradient gives a flat plateau at the size of the bug, so
            # the shape of the sweep is stronger evidence than the floor alone.
            v_shaped = errors.index(best) not in (0, len(errors) - 1)
            per_direction.append({"analytic": analytic, "sweep": sweep,
                                  "best_relative_error": best, "v_shaped": v_shaped})
        worst = max(d["best_relative_error"] for d in per_direction)
        shaped = all(d["v_shaped"] for d in per_direction)
        report[f"q{(degree + 1) ** 2}"] = {
            "directions": per_direction, "worst_best_relative_error": worst,
            "v_shaped": shaped, "coefficients": basis.coefficient_count,
            "passed": worst <= 1e-5 and shaped,
        }
        print(f"  gate 2  q={(degree + 1) ** 2}: worst {worst:.3e}, V-shaped {shaped}",
              flush=True)
    return report


# -- gates 3 to 5 ---------------------------------------------------------


def gate_twin(arguments) -> dict:
    """Recover a known `a_true` through the exact forward model."""

    report: dict[str, object] = {}
    for degree in arguments.degrees:
        grid, kinematics, material, preconditioner, basis = build(
            arguments.twin_pixels, arguments.patches, degree
        )
        peak = arguments.peak_increment
        truth = smooth_coefficients(basis, peak, 5)
        inverse = LocalCoefficientInverse(
            material=material, kinematics=kinematics, grid=grid, basis=basis,
            boundary_displacement=uniaxial_boundary(grid, arguments.strain),
            observed_displacement=np.zeros((grid.nx + 1, grid.ny + 1, 2)),
            preconditioner=preconditioner,
            projection=AdmissibleProjection(safety=arguments.safety),
        )
        settle(inverse, material, kinematics, grid, preconditioner, truth,
               arguments.settle_increments, arguments.strain_per_increment)
        target, _, _ = inverse.evaluate(truth)
        inverse.observed_displacement = target.displacement.copy()
        truth_field = target.plastic_increment.copy()

        start = np.zeros(basis.coefficient_shape)
        start[:, :, 0, 0] = 0.5 * peak
        history: list[dict[str, float]] = []
        started = time.time()

        truth_norm = max(float(np.linalg.norm(truth_field)), 1e-300)
        # Displacements are in millimetres, so the objective sits near 1e-13 and
        # L-BFGS-B's relative test `(f_k - f_k+1) / max(|f_k|, |f_k+1|, 1)`
        # silently becomes an ABSOLUTE one. Left unscaled it stops while still
        # making 0.1 % relative progress per step, which reads as a converged
        # optimisation and is not one. Scaling by a fixed data norm -- not by the
        # current iterate -- restores the intended meaning of ftol.
        observation_scale = max(
            0.5 * float(np.sum(target.displacement[1:-1, 1:-1] ** 2)), 1e-300
        )

        def objective_and_gradient(
            flat: np.ndarray, basis=basis, peak=peak, inverse=inverse,
            truth_field=truth_field, truth_norm=truth_norm, history=history,
            observation_scale=observation_scale,
        ) -> tuple[float, np.ndarray]:
            values = flat.reshape(basis.coefficient_shape) * peak
            evaluation, gradient = inverse.gradient(values)
            # Tracked per evaluation, not only at the end: an objective that
            # keeps falling while this plateaus is the signature of a
            # near-nullspace, and is the difference between "not converged yet"
            # and "not identifiable from displacement".
            error = float(
                np.linalg.norm(evaluation.plastic_increment - truth_field) / truth_norm
            )
            history.append({
                "objective": evaluation.objective,
                "field_relative_error": error,
                "newton": evaluation.newton_iterations,
                "krylov": evaluation.krylov_iterations,
                "clipped_fraction": evaluation.clipped_fraction,
                "admissibility_margin": evaluation.admissibility_margin,
            })
            print(f"    step {len(history):>3}  J={evaluation.objective:.6e}  "
                  f"field={error:.4f}  "
                  f"N={evaluation.newton_iterations}  K={evaluation.krylov_iterations}  "
                  f"clipped={evaluation.clipped_fraction:.3f}  "
                  f"margin={evaluation.admissibility_margin:.3f}", flush=True)
            return (
                evaluation.objective / observation_scale,
                (gradient * peak / observation_scale).ravel(),
            )

        outcome = minimize(
            objective_and_gradient, (start / peak).ravel(), jac=True,
            method="L-BFGS-B",
            options={"maxiter": arguments.iterations, "ftol": 1e-16, "gtol": 1e-14},
        )
        seconds = time.time() - started
        recovered = outcome.x.reshape(basis.coefficient_shape) * peak
        final, _, _ = inverse.evaluate(recovered)
        field_error = float(
            np.linalg.norm(final.plastic_increment - truth_field)
            / max(np.linalg.norm(truth_field), 1e-300)
        )
        coefficient_error = float(
            np.linalg.norm(recovered - truth) / max(np.linalg.norm(truth), 1e-300)
        )
        newtons = [row["newton"] for row in history]
        decades = (
            np.log10(history[0]["objective"] / final.objective)
            if final.objective > 0 and history else float("inf")
        )
        entry = {
            "coefficients": basis.coefficient_count,
            "initial_objective": history[0]["objective"] if history else None,
            "final_objective": final.objective,
            "decades": float(decades),
            "field_relative_error": field_error,
            "coefficient_relative_error": coefficient_error,
            "median_newton": float(np.median(newtons)),
            "fraction_at_most_two_newton": float(np.mean(np.array(newtons) <= 2)),
            "maximum_admissibility_margin": max(
                row["admissibility_margin"] for row in history
            ),
            "maximum_clipped_fraction": max(row["clipped_fraction"] for row in history),
            "evaluations": len(history),
            "seconds": seconds,
            "history": history,
        }
        entry["passed_gate_3"] = decades >= 3.0 and (
            field_error <= 0.05 if degree == 0 else True
        )
        entry["passed_gate_5"] = (
            entry["median_newton"] <= 2.0
            and entry["fraction_at_most_two_newton"] >= 0.80
        )
        report[f"q{(degree + 1) ** 2}"] = entry
        print(f"  gate 3  q={(degree + 1) ** 2}: {decades:.2f} decades, field error "
              f"{field_error:.4f}, coefficient error {coefficient_error:.4f}", flush=True)
        print(f"  gate 5  q={(degree + 1) ** 2}: median Newton "
              f"{entry['median_newton']:.1f}, "
              f"{entry['fraction_at_most_two_newton']:.0%} at most two", flush=True)
    return report


def gate_spectrum(arguments) -> dict:
    """The singular spectrum of `du/da`: identifiability without an optimiser.

    A descent that fails to recover a field can always be blamed on the
    optimiser. A spectrum cannot. If the singular values of the
    parameter-to-observable map span many decades, the small ones are
    combinations of local coefficients the displacement does not see, and the
    representation is not identifiable in those directions however the
    optimisation is run.
    """

    report: dict[str, object] = {}
    for degree in arguments.degrees:
        grid, kinematics, material, preconditioner, basis = build(
            arguments.spectrum_pixels, arguments.spectrum_patches, degree
        )
        peak = arguments.peak_increment
        truth = smooth_coefficients(basis, peak, 5)
        inverse = LocalCoefficientInverse(
            material=material, kinematics=kinematics, grid=grid, basis=basis,
            boundary_displacement=uniaxial_boundary(grid, arguments.strain),
            observed_displacement=np.zeros((grid.nx + 1, grid.ny + 1, 2)),
            preconditioner=preconditioner,
            projection=AdmissibleProjection(safety=arguments.safety),
        )
        settle(inverse, material, kinematics, grid, preconditioner, truth,
               arguments.settle_increments, arguments.strain_per_increment)
        started = time.time()
        _, columns = inverse.sensitivity_matrix(truth)
        singular = np.linalg.svd(columns, compute_uv=False)
        condition = float(singular[0] / max(singular[-1], 1e-300))
        # How many directions carry a given share of the leading sensitivity.
        thresholds = {}
        for decades in (1, 2, 3, 4, 6):
            thresholds[f"above_1e-{decades}"] = int(
                np.sum(singular >= singular[0] * 10.0**-decades)
            )
        entry = {
            "coefficients": basis.coefficient_count,
            "singular_values": singular.tolist(),
            "condition_number": condition,
            "effective_rank": thresholds,
            "seconds": time.time() - started,
        }
        report[f"q{(degree + 1) ** 2}"] = entry
        print(f"  spectrum q={(degree + 1) ** 2}: {basis.coefficient_count} coefficients, "
              f"condition {condition:.3e}", flush=True)
        print(f"    directions above 1e-1 / 1e-2 / 1e-3 / 1e-4 / 1e-6 of the leading: "
              f"{thresholds['above_1e-1']} / {thresholds['above_1e-2']} / "
              f"{thresholds['above_1e-3']} / {thresholds['above_1e-4']} / "
              f"{thresholds['above_1e-6']}", flush=True)
    return report


def gate_gauss_newton(arguments) -> dict:
    """What the data allow, with the optimiser taken out of the question.

    L-BFGS-B stalling and the problem being unidentifiable look identical from a
    convergence plot. They are not the same thing, and a few exact Gauss-Newton
    steps -- the least-squares solution through the SVD of the sensitivity
    matrix, no line search, no curvature estimate -- separate them. If this
    recovers the field, every remaining gap is the optimiser's; if it does not,
    no optimiser will.
    """

    report: dict[str, object] = {}
    for degree in arguments.degrees:
        grid, kinematics, material, preconditioner, basis = build(
            arguments.spectrum_pixels, arguments.spectrum_patches, degree
        )
        peak = arguments.peak_increment
        truth = smooth_coefficients(basis, peak, 5)
        inverse = LocalCoefficientInverse(
            material=material, kinematics=kinematics, grid=grid, basis=basis,
            boundary_displacement=uniaxial_boundary(grid, arguments.strain),
            observed_displacement=np.zeros((grid.nx + 1, grid.ny + 1, 2)),
            preconditioner=preconditioner,
            projection=AdmissibleProjection(safety=arguments.safety),
        )
        settle(inverse, material, kinematics, grid, preconditioner, truth,
               arguments.settle_increments, arguments.strain_per_increment)
        target, _, _ = inverse.evaluate(truth)
        inverse.observed_displacement = target.displacement.copy()
        truth_field = target.plastic_increment.copy()
        truth_norm = max(float(np.linalg.norm(truth_field)), 1e-300)

        current = np.zeros(basis.coefficient_shape)
        current[:, :, 0, 0] = 0.5 * peak
        steps = []
        for iteration in range(arguments.gauss_newton_steps):
            evaluation, columns = inverse.sensitivity_matrix(current)
            residual = (
                evaluation.displacement - inverse.observed_displacement
            )[1:-1, 1:-1].ravel()
            correction, *_ = np.linalg.lstsq(columns, -residual, rcond=None)
            current = current + correction.reshape(basis.coefficient_shape)
            after, _, _ = inverse.evaluate(current)
            error = float(
                np.linalg.norm(after.plastic_increment - truth_field) / truth_norm
            )
            steps.append({
                "iteration": iteration + 1,
                "objective_before": evaluation.objective,
                "objective_after": after.objective,
                "field_relative_error": error,
            })
            print(f"    gauss-newton {iteration + 1}: J {evaluation.objective:.4e} -> "
                  f"{after.objective:.4e}, field error {error:.4f}", flush=True)
        report[f"q{(degree + 1) ** 2}"] = {
            "coefficients": basis.coefficient_count,
            "steps": steps,
            "final_field_relative_error": steps[-1]["field_relative_error"],
        }
    return report


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--gate", default="all",
                        choices=("transpose", "gradient", "twin", "spectrum",
                                 "gauss-newton", "all"))
    parser.add_argument("--spectrum-pixels", type=int, default=48)
    parser.add_argument("--gauss-newton-steps", type=int, default=3)
    parser.add_argument("--spectrum-patches", type=int, default=6)
    parser.add_argument("--small-pixels", type=int, default=32)
    parser.add_argument("--small-patches", type=int, default=4)
    parser.add_argument("--twin-pixels", type=int, default=64)
    parser.add_argument("--patches", type=int, default=8)
    parser.add_argument("--degrees", nargs="+", type=int, default=[0, 1])
    parser.add_argument("--strain", type=float, default=1.8e-3)
    parser.add_argument("--strain-per-increment", type=float, default=1.2e-3)
    parser.add_argument("--settle-increments", type=int, default=2)
    parser.add_argument("--peak-increment", type=float, default=4.0e-4)
    parser.add_argument("--safety", type=float, default=0.9)
    parser.add_argument("--iterations", type=int, default=60)
    parser.add_argument("--output", type=Path, required=True)
    arguments = parser.parse_args()

    report: dict[str, object] = {}
    if arguments.gate in ("transpose", "all"):
        print("gate 1 -- the transpose is the transpose", flush=True)
        report["gate_1_transpose"] = gate_transpose(arguments)
    if arguments.gate in ("gradient", "all"):
        print("gate 2 -- the gradient is the derivative of the objective", flush=True)
        report["gate_2_gradient"] = gate_gradient(arguments)
    if arguments.gate in ("twin", "all"):
        print("gates 3-5 -- twin recovery, admissibility, warm regime", flush=True)
        report["gate_3_twin"] = gate_twin(arguments)
    if arguments.gate in ("spectrum", "all"):
        print("identifiability -- the spectrum of the parameter-to-observable map",
              flush=True)
        report["identifiability_spectrum"] = gate_spectrum(arguments)
    if arguments.gate in ("gauss-newton", "all"):
        print("identifiability -- exact Gauss-Newton, the optimiser removed", flush=True)
        report["gauss_newton"] = gate_gauss_newton(arguments)

    arguments.output.parent.mkdir(parents=True, exist_ok=True)
    arguments.output.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n", "utf-8")
    print(f"\nwrote {arguments.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
