"""Object-based comparison tools for observed EVM fields.

These modules answer "which candidate reproduces the observed bands", which a
global error cannot. They operate on fields only: nothing here runs mechanics,
selects a material parameter, or touches an archived result.

Geometry is defined from the DIC field alone and then frozen, so every
candidate is measured against the same objects.
"""

from fem_inhouse.validation.band_geometry import (
    BandObject,
    NetworkMetrics,
    band_corridor,
    count_enclosed_holes,
    label_band_objects,
    network_metrics,
    order_centreline,
    prune_skeleton_spurs,
    quantile_thresholds,
    resample_polyline,
    smooth_centreline,
    tangents_and_normals,
    zhang_suen_thinning,
)
from fem_inhouse.validation.band_profiles import (
    BackgroundEstimate,
    NormalProfile,
    WidthMeasurement,
    WidthStatus,
    compare_profiles,
    continuity_metrics,
    estimate_background,
    excess_profile,
    measure_amplitude,
    measure_position,
    measure_width,
    sample_normal_profile,
    summarise,
)
from fem_inhouse.validation.falsification_cases import (
    PerturbedField,
    add_spurious_band,
    change_band_width,
    interrupt_region,
    remove_region,
    scale_amplitude,
    standard_cases,
    translate_field,
)
from fem_inhouse.validation.fractions_skill_score import (
    SkillCurve,
    active_fraction_field,
    fractions_skill_score,
    minimum_skilful_scale,
    skill_curve,
    skill_table,
)
from fem_inhouse.validation.otsu_morphology import (
    FieldMorphology,
    ObjectMorphology,
    describe_morphology,
    morphology_distance,
    otsu_threshold,
)
from fem_inhouse.validation.pareto_decision import (
    DecisionReport,
    EliminationRule,
    Sense,
    apply_elimination,
    decide,
    dominates,
    pareto_front,
    worst_band_vector,
)
from fem_inhouse.validation.residual_structure import (
    EnergyPartition,
    classify_residual,
    directional_variogram,
    energy_partition,
    radial_power_spectrum,
    residual_associations,
    signed_residual,
)
from fem_inhouse.validation.spatial_bootstrap import (
    BootstrapDesign,
    PairwiseResult,
    block_indices,
    block_length_sensitivity,
    classify_probability,
    compare_pair,
    paired_band_bootstrap,
)

__all__ = [
    "BackgroundEstimate",
    "BandObject",
    "BootstrapDesign",
    "DecisionReport",
    "EliminationRule",
    "EnergyPartition",
    "FieldMorphology",
    "NetworkMetrics",
    "NormalProfile",
    "ObjectMorphology",
    "PairwiseResult",
    "PerturbedField",
    "Sense",
    "SkillCurve",
    "WidthMeasurement",
    "WidthStatus",
    "active_fraction_field",
    "add_spurious_band",
    "apply_elimination",
    "band_corridor",
    "block_indices",
    "block_length_sensitivity",
    "change_band_width",
    "classify_probability",
    "classify_residual",
    "compare_pair",
    "compare_profiles",
    "continuity_metrics",
    "count_enclosed_holes",
    "decide",
    "describe_morphology",
    "directional_variogram",
    "dominates",
    "energy_partition",
    "estimate_background",
    "excess_profile",
    "fractions_skill_score",
    "interrupt_region",
    "label_band_objects",
    "measure_amplitude",
    "measure_position",
    "measure_width",
    "minimum_skilful_scale",
    "morphology_distance",
    "network_metrics",
    "order_centreline",
    "otsu_threshold",
    "paired_band_bootstrap",
    "pareto_front",
    "prune_skeleton_spurs",
    "quantile_thresholds",
    "radial_power_spectrum",
    "remove_region",
    "resample_polyline",
    "residual_associations",
    "sample_normal_profile",
    "scale_amplitude",
    "signed_residual",
    "skill_curve",
    "skill_table",
    "smooth_centreline",
    "standard_cases",
    "summarise",
    "tangents_and_normals",
    "translate_field",
    "worst_band_vector",
    "zhang_suen_thinning",
]
